FROM golang:1.19-alpine3.16

WORKDIR /app
ENV GO111MODULE=on
ENV CGO_ENABLED=0

RUN apk add -U --no-cache protobuf-dev make
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

USER 1000:1000

CMD ["tail", "-f", "/dev/null"]
